"""Wire `code` strings for Modulr.Core MVP (errors and success).

Aligned with plan/operations.md and plan/validation-and-signing.md.
"""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Stable error codes returned in response envelopes."""

    # Request / envelope
    MALFORMED_JSON = "MALFORMED_JSON"
    INVALID_REQUEST = "INVALID_REQUEST"
    MALFORMED_ENVELOPE = "MALFORMED_ENVELOPE"
    SIGNATURE_MISSING = "SIGNATURE_MISSING"
    INVALID_FIELD = "INVALID_FIELD"

    # Routing / version
    TARGET_MODULE_MISMATCH = "TARGET_MODULE_MISMATCH"
    UNSUPPORTED_OPERATION = "UNSUPPORTED_OPERATION"
    MODULE_VERSION_NOT_FOUND = "MODULE_VERSION_NOT_FOUND"
    MODULE_VERSION_UNSUPPORTED = "MODULE_VERSION_UNSUPPORTED"

    # Time and size
    INVALID_EXPIRY = "INVALID_EXPIRY"
    MESSAGE_EXPIRED = "MESSAGE_EXPIRED"
    EXPIRY_WINDOW_TOO_LARGE = "EXPIRY_WINDOW_TOO_LARGE"
    TIMESTAMP_FUTURE_SKEW_EXCEEDED = "TIMESTAMP_FUTURE_SKEW_EXCEEDED"
    MESSAGE_TOO_LARGE = "MESSAGE_TOO_LARGE"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"

    # Integrity / crypto
    PAYLOAD_HASH_MISMATCH = "PAYLOAD_HASH_MISMATCH"
    SIGNATURE_INVALID = "SIGNATURE_INVALID"
    PUBLIC_KEY_INVALID = "PUBLIC_KEY_INVALID"
    MESSAGE_ID_CONFLICT = "MESSAGE_ID_CONFLICT"

    # Payload / policy
    PAYLOAD_INVALID = "PAYLOAD_INVALID"
    UNAUTHORIZED = "UNAUTHORIZED"
    MODULE_NOT_FOUND = "MODULE_NOT_FOUND"
    MODULE_ALREADY_REGISTERED = "MODULE_ALREADY_REGISTERED"
    NAME_NOT_FOUND = "NAME_NOT_FOUND"
    NAME_ALREADY_BOUND = "NAME_ALREADY_BOUND"
    IDENTITY_NOT_FOUND = "IDENTITY_NOT_FOUND"

    # Operation-specific
    INVALID_MODULE_NAME = "INVALID_MODULE_NAME"
    INVALID_ROUTE = "INVALID_ROUTE"
    INVALID_NAME = "INVALID_NAME"
    IDENTITY_MISMATCH = "IDENTITY_MISMATCH"
    INVALID_STATUS = "INVALID_STATUS"
    METRICS_TOO_LARGE = "METRICS_TOO_LARGE"

    # HTTP / deployment (until operation handlers land)
    OPERATION_NOT_IMPLEMENTED = "OPERATION_NOT_IMPLEMENTED"
    INTERNAL_ERROR = "INTERNAL_ERROR"

    # Idempotency / replay
    REPLAY_RESPONSE_UNAVAILABLE = "REPLAY_RESPONSE_UNAVAILABLE"


class SuccessCode(StrEnum):
    """Success `code` values for MVP operations."""

    MODULE_REGISTERED = "MODULE_REGISTERED"
    MODULE_FOUND = "MODULE_FOUND"
    NAME_RESOLVED = "NAME_RESOLVED"
    NAME_REGISTERED = "NAME_REGISTERED"
    ORG_REGISTERED = "ORG_REGISTERED"
    NAME_REVERSE_RESOLVED = "NAME_REVERSE_RESOLVED"
    HEARTBEAT_RECORDED = "HEARTBEAT_RECORDED"
